FROM golang:alpine AS build-env

RUN apk update
RUN apk add --no-cache curl make git libc-dev bash gcc linux-headers eudev-dev python3

WORKDIR /go/src/github.com/allinbits/cosmos-cash-poa

COPY . .

RUN make install

## Final image
#FROM gcr.io/distroless/base:latest
FROM alpine:edge

RUN apk add --update ca-certificates
WORKDIR /root

COPY --from=build-env /go/bin/poad /usr/bin/poad
COPY --from=build-env /go/bin/poacli /usr/bin/poacli

EXPOSE 26656 26657 1317 9090

